FROM python:3.9-slim

WORKDIR /app

# تثبيت المكتبات اللازمة
RUN pip install streamlit pandas sqlalchemy psycopg2-binary plotly

# نسخ ملف الداشبورد
COPY dashboard.py .

# فتح بورت ستريم ليت الافتراضي
EXPOSE 8501

# أمر التشغيل (مع مراعاة الـ headless mode عشان يشتغل جوه دوكر)
CMD ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]